"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import sys
from setuptools import setup

mainscript = 'wixed/main.py' 

if sys.platform == 'darwin':
    PLIST = dict(
        CFBundleDisplayName='Wixed',
        CFBundleName='Wixed',
    )
    extra_options = dict(
        setup_requires=['py2app'],
        app=[mainscript],
        options={'py2app': dict(
            argv_emulation=True,
            iconfile='wixed.icns',
            plist=PLIST,
        )},
        
    )
elif sys.platform == 'win32':
    extra_options = dict(
         setup_requires=['py2exe'],
         app=[mainscript],
     )
else:
     extra_options = dict(
         # Normally unix-like platforms will use "setup.py install"
         # and install the main script as such
         scripts=[mainscript],
     )

DATA_FILES = []

setup(
    name='wixed',
    version='0.1dev',
    data_files=DATA_FILES,
    packages=['wixed'],
    **extra_options
)
